[project]
name = "framework"
version = "0.1.0"
description = "An autograd framework for ai Training"
readme = "README.md"
requires-python = "==3.13.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pyvis>=0.3.2",
]

[dependency-groups]
dev = [
    "ty>=0.0.5",
]
